### ISSUE TITLE
Add import in documentation

### ISSUE THREAD

**Issue by MathisBarre** [PaulLeCam/react-leaflet#789]
Hey, it's so great that leaflet have a react integration but honestly the documentation isn't the best I've seen.
It seems to be better with the new v3 documentation but, could you add import to your examples ?

**Comment by aleksandr-vin** [comment]
And mentioning how to set height, like:
```css
.leaflet-container {
    height: 100vh;
}
```
